extends Sprite
# Github Co-Pilot generated ==================================================================================

# array of robot greetings
var greetings = ['hello', 'hi', 'hola', 'greetings', 'welcome']

# array of robot questions
var questions = ['how are you?', 'how is your day?', 'good?', 'ok?']

# array of responses to questions
var responses = ['good', 'ok', 'I am good', 'not bad']

# array of goodbye words
var goodbyes = ['bye', 'goodbye', 'see you later', 'goodbye']

# array of silly puns
var silly = ['lol', 'haha', 'ha', 'hahaha', 'hehe']

# array of vague hints
var hints = ['I don\'t know', 'I am not sure', 'I am not sure about that', 'I am not sure about that']

# array of quests
var quests = ['what is your quest?', 'what do you seek?', 'what do you want?', 'what do you want to know?']


# The rest were not generated by Co-Pilot ====================================================================

var mystery_hints = ['Have you checked the next building?', "The Purple Dove knows what you did", "Re-check the quest log....is there a quest log?"]

var robot_names = ['RoboPal', 'Sam', 'Who\'s Askin\'?', 'NCC1475', 'D.A.V.E']

enum {
	NEVER_MET,
	MET,
	FIRST_CASE
}

var roboState = NEVER_MET

func _unhandled_input(event):
	if event is InputEventMouseButton and event.pressed and event.button_index == BUTTON_LEFT:
		if get_rect().has_point(to_local(event.position)):
			var world = get_tree().current_scene
			if world.has_node("RobotChat"):
				var roboChat = world.get_node("RobotChat")
				roboChat.queue_free()
			else:
				var RoboChat = load("res://RoboPal/RobotChat.tscn")
				var roboChat = RoboChat.instance()
				world.add_child(roboChat)
				var chatBox = roboChat.get_node("Label")
				match(roboState):
					NEVER_MET:
						chatBox.text = greetings[randi() % greetings.size()]
